### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Rajdp07**
Added my own Frontend Project

### CODE REVIEW

**Comment by aymenkhs** [comment]
Hey, we reviewed your Pull request, it's all good, but can you just add a small description of the project in your README? Just explain briefly what your project is about in on line or two

**Comment by Rajdp07** [comment]
Ok

**Review by aymenkhs — CHANGES_REQUESTED** [review]
Just provide a small description of the project

**Comment by Rajdp07** [comment]
I have changed and added a description of this project in the Readme. Please review it again.

**Review by aymenkhs — APPROVED** [review]

**Pull request merged**
