### PR TITLE
Water Reminder

### PR DESCRIPTION
**Pull request by mohdanwaroddin**

### CODE REVIEW

**Comment by IliesChibane** [comment]
Your project is great, unfortunately your pull is on the wrong directory, please pull your project in the "your_project" directory

**Review by IliesChibane — CHANGES_REQUESTED** [review]
Your project is great, unfortunately your pull is on the wrong directory, please pull your project in the "your_project" directory

**Comment by mohdanwaroddin** [comment]
ok

**Comment by mohdanwaroddin** [comment]
I will....

**Pull request merged**
